baseURL = "https://weixinfree.github.io/blog/"
languageCode = "zh-rCN"
title = "Details makes perfect"
pygmentsCodeFences=true

theme = "kiss"
themesDir = "themes"

copyright = "&copy; <a href=\"https://github.com/weixinfree\">WangWei</a> 2018"
disqusShortname = "shortname"
googleAnalytics = ""
Paginate = 6 # Number of posts per page
enableRobotsTXT = true

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "WangWei" # Author full name
authorEmail = "2317073226@qq.com" # Author email

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Details makes perfect" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = ""
github = "weixinfree"
email = "2317073226@qq.com"
linkedin = ""
facebook = ""
instagram = ""
codepen = ""
rss = "index.xml" # Add this to show RSS button in social.

[params.matomoAnalytics]
siteID = 1
rootURL = "//matomo.example.com/"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true